#include "Map.h"
#include <iostream>
#include "raylib.h"
#include "rlgl.h"
using namespace std;

// Constructor: sets the map's width and height
Map::Map() {
    
}

// Converts world coordinates (x, y) to screen coordinates using isometric transformation
Vector2 Map::world_to_screen(float x, float y) {
    Matrix2x2 transform = {
        static_cast<float>(0.5 * 64), static_cast<float>(-0.5 * 64),
        static_cast<float>(0.5 * 32), static_cast<float>(0.5 * 32)
    };

    return {
        static_cast<float>(x * transform.m00 + y * transform.m01) ,
        static_cast<float>(x * transform.m10 + y * transform.m11) 
    };
}

void Map::init_map() {
    borders_tiles.push_back(Tile({12,-2},0,GRAY));
    walkable_tiles.push_back(Tile({13,-2},0,GRAY));
    walkable_tiles.push_back(Tile({14,-2},0,GRAY));
    walkable_tiles.push_back(Tile({15,-2},0,GRAY));
    borders_tiles.push_back(Tile({15,-2},0,GRAY));
    walkable_tiles.push_back(Tile({16,-2},0,GRAY));
    walkable_tiles.push_back(Tile({17,-2},0,GRAY));
    walkable_tiles.push_back(Tile({18,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-2},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-2},0,GRAY));
    walkable_tiles.push_back(Tile({26,-2},0,GRAY));
    walkable_tiles.push_back(Tile({27,-2},0,GRAY));
    walkable_tiles.push_back(Tile({28,-2},0,GRAY));
    walkable_tiles.push_back(Tile({29,-2},0,GRAY));
    borders_tiles.push_back(Tile({29,-2},0,GRAY));
    walkable_tiles.push_back(Tile({30,-2},0,GRAY));
    walkable_tiles.push_back(Tile({31,-2},0,GRAY));
    walkable_tiles.push_back(Tile({32,-2},0,GRAY));
    walkable_tiles.push_back(Tile({33,-2},0,GRAY));
    walkable_tiles.push_back(Tile({34,-2},0,GRAY));
    walkable_tiles.push_back(Tile({35,-2},0,GRAY));
    walkable_tiles.push_back(Tile({36,-2},0,GRAY));
    walkable_tiles.push_back(Tile({37,-2},0,GRAY));
    walkable_tiles.push_back(Tile({38,-2},0,GRAY));
    walkable_tiles.push_back(Tile({39,-2},0,GRAY));
    walkable_tiles.push_back(Tile({40,-2},0,GRAY));
    borders_tiles.push_back(Tile({40,-2},0,GRAY));

    borders_tiles.push_back(Tile({12,-3},0,GRAY));
    walkable_tiles.push_back(Tile({13,-3},0,GRAY));
    walkable_tiles.push_back(Tile({14,-3},0,GRAY));
    borders_tiles.push_back(Tile({14,-3},0,GRAY));
    walkable_tiles.push_back(Tile({15,-3},0,GRAY));
    walkable_tiles.push_back(Tile({16,-3},0,GRAY));
    walkable_tiles.push_back(Tile({17,-3},0,GRAY));
    walkable_tiles.push_back(Tile({18,-3},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-3},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-3},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-3},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-3},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-3},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-3},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-3},0,GRAY));
    walkable_tiles.push_back(Tile({26,-3},0,GRAY));
    walkable_tiles.push_back(Tile({27,-3},0,GRAY));
    walkable_tiles.push_back(Tile({28,-3},0,GRAY));
    borders_tiles.push_back(Tile({28,-3},0,GRAY));
    walkable_tiles.push_back(Tile({29,-3},0,GRAY));
    walkable_tiles.push_back(Tile({30,-3},0,GRAY));
    walkable_tiles.push_back(Tile({31,-3},0,GRAY));
    walkable_tiles.push_back(Tile({32,-3},0,GRAY));
    walkable_tiles.push_back(Tile({33,-3},0,GRAY));
    walkable_tiles.push_back(Tile({34,-3},0,GRAY));
    walkable_tiles.push_back(Tile({35,-3},0,GRAY));
    walkable_tiles.push_back(Tile({36,-3},0,GRAY));
    walkable_tiles.push_back(Tile({37,-3},0,GRAY));
    walkable_tiles.push_back(Tile({38,-3},0,GRAY));
    walkable_tiles.push_back(Tile({39,-3},0,GRAY));
    walkable_tiles.push_back(Tile({40,-3},0,GRAY));
    borders_tiles.push_back(Tile({40,-3},0,GRAY));

    borders_tiles.push_back(Tile({12,-4},0,GRAY));
    walkable_tiles.push_back(Tile({13,-4},0,GRAY));
    borders_tiles.push_back(Tile({13,-4},0,GRAY));
    walkable_tiles.push_back(Tile({14,-4},0,GRAY));
    walkable_tiles.push_back(Tile({15,-4},0,GRAY));
    walkable_tiles.push_back(Tile({16,-4},0,GRAY));
    walkable_tiles.push_back(Tile({17,-4},0,GRAY));
    walkable_tiles.push_back(Tile({18,-4},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-4},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-4},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-4},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-4},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-4},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-4},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-4},0,GRAY));
    walkable_tiles.push_back(Tile({26,-4},0,GRAY));
    walkable_tiles.push_back(Tile({27,-4},0,GRAY));
    borders_tiles.push_back(Tile({27,-4},0,GRAY));
    walkable_tiles.push_back(Tile({28,-4},0,GRAY));
    walkable_tiles.push_back(Tile({29,-4},0,GRAY));
    walkable_tiles.push_back(Tile({30,-4},0,GRAY));
    walkable_tiles.push_back(Tile({31,-4},0,GRAY));
    walkable_tiles.push_back(Tile({32,-4},0,GRAY));
    walkable_tiles.push_back(Tile({33,-4},0,GRAY));
    walkable_tiles.push_back(Tile({34,-4},0,GRAY));
    walkable_tiles.push_back(Tile({35,-4},0,GRAY));
    walkable_tiles.push_back(Tile({36,-4},0,GRAY));
    walkable_tiles.push_back(Tile({37,-4},0,GRAY));
    walkable_tiles.push_back(Tile({38,-4},0,GRAY));
    walkable_tiles.push_back(Tile({39,-4},0,GRAY));
    walkable_tiles.push_back(Tile({40,-4},0,GRAY));
    borders_tiles.push_back(Tile({40,-4},0,GRAY));

    borders_tiles.push_back(Tile({12,-5},0,GRAY));
    walkable_tiles.push_back(Tile({13,-5},0,GRAY));
    walkable_tiles.push_back(Tile({14,-5},0,GRAY));
    walkable_tiles.push_back(Tile({15,-5},0,GRAY));
    walkable_tiles.push_back(Tile({16,-5},0,GRAY));
    walkable_tiles.push_back(Tile({17,-5},0,GRAY));
    walkable_tiles.push_back(Tile({18,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-5},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-5},0,GRAY));
    walkable_tiles.push_back(Tile({26,-5},0,GRAY));
    borders_tiles.push_back(Tile({26,-5},0,GRAY));
    walkable_tiles.push_back(Tile({27,-5},0,GRAY));
    walkable_tiles.push_back(Tile({28,-5},0,GRAY));
    walkable_tiles.push_back(Tile({29,-5},0,GRAY));
    walkable_tiles.push_back(Tile({30,-5},0,GRAY));
    walkable_tiles.push_back(Tile({31,-5},0,GRAY));
    walkable_tiles.push_back(Tile({32,-5},0,GRAY));
    walkable_tiles.push_back(Tile({33,-5},0,GRAY));
    walkable_tiles.push_back(Tile({34,-5},0,GRAY));
    walkable_tiles.push_back(Tile({35,-5},0,GRAY));
    walkable_tiles.push_back(Tile({36,-5},0,GRAY));
    walkable_tiles.push_back(Tile({37,-5},0,GRAY));
    walkable_tiles.push_back(Tile({38,-5},0,GRAY));
    walkable_tiles.push_back(Tile({39,-5},0,GRAY));
    walkable_tiles.push_back(Tile({40,-5},0,GRAY));
    borders_tiles.push_back(Tile({40,-5},0,GRAY));

    borders_tiles.push_back(Tile({12,-6},0,GRAY));
    walkable_tiles.push_back(Tile({13,-6},0,GRAY));
    walkable_tiles.push_back(Tile({14,-6},0,GRAY));
    walkable_tiles.push_back(Tile({15,-6},0,GRAY));
    walkable_tiles.push_back(Tile({16,-6},0,GRAY));
    walkable_tiles.push_back(Tile({17,-6},0,GRAY));
    walkable_tiles.push_back(Tile({18,-6},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-6},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-6},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-6},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-6},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-6},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-6},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-6},0,GRAY));
    borders_tiles.push_back(Tile({25,-6},0,GRAY));
    walkable_tiles.push_back(Tile({26,-6},0,GRAY));
    walkable_tiles.push_back(Tile({27,-6},0,GRAY));
    walkable_tiles.push_back(Tile({28,-6},0,GRAY));
    walkable_tiles.push_back(Tile({29,-6},0,GRAY));
    walkable_tiles.push_back(Tile({30,-6},0,GRAY));
    walkable_tiles.push_back(Tile({31,-6},0,GRAY));
    walkable_tiles.push_back(Tile({32,-6},0,GRAY));
    walkable_tiles.push_back(Tile({33,-6},0,GRAY));
    walkable_tiles.push_back(Tile({34,-6},0,GRAY));
    walkable_tiles.push_back(Tile({35,-6},0,GRAY));
    walkable_tiles.push_back(Tile({36,-6},0,GRAY));
    walkable_tiles.push_back(Tile({37,-6},0,GRAY));
    walkable_tiles.push_back(Tile({38,-6},0,GRAY));
    walkable_tiles.push_back(Tile({39,-6},0,GRAY));
    walkable_tiles.push_back(Tile({40,-6},0,GRAY));
    borders_tiles.push_back(Tile({40,-6},0,GRAY));

    borders_tiles.push_back(Tile({12,-7},0,GRAY));
    walkable_tiles.push_back(Tile({13,-7},0,GRAY));
    walkable_tiles.push_back(Tile({14,-7},0,GRAY));
    walkable_tiles.push_back(Tile({15,-7},0,GRAY));
    walkable_tiles.push_back(Tile({16,-7},0,GRAY));
    walkable_tiles.push_back(Tile({17,-7},0,GRAY));
    walkable_tiles.push_back(Tile({18,-7},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-7},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-7},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-7},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-7},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-7},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-7},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-7},0,GRAY));
    borders_tiles.push_back(Tile({25,-7},1,GRAY));
    walkable_tiles.push_back(Tile({26,-7},0,GRAY));
    borders_tiles.push_back(Tile({26,-7},0,GRAY));
    walkable_tiles.push_back(Tile({27,-7},0,GRAY));
    borders_tiles.push_back(Tile({27,-7},0,GRAY));
    walkable_tiles.push_back(Tile({28,-7},0,GRAY));
    borders_tiles.push_back(Tile({28,-7},1,GRAY));
    walkable_tiles.push_back(Tile({29,-7},0,GRAY));
    borders_tiles.push_back(Tile({29,-7},0,GRAY));
    walkable_tiles.push_back(Tile({30,-7},0,GRAY));
    borders_tiles.push_back(Tile({30,-7},1,GRAY));
    walkable_tiles.push_back(Tile({31,-7},0,GRAY));
    borders_tiles.push_back(Tile({31,-7},0,GRAY));
    walkable_tiles.push_back(Tile({32,-7},0,GRAY));
    borders_tiles.push_back(Tile({32,-7},0,GRAY));
    walkable_tiles.push_back(Tile({33,-7},0,GRAY));
    borders_tiles.push_back(Tile({33,-7},0,GRAY));
    walkable_tiles.push_back(Tile({34,-7},0,GRAY));
    borders_tiles.push_back(Tile({34,-7},0,GRAY));
    walkable_tiles.push_back(Tile({35,-7},0,GRAY));
    borders_tiles.push_back(Tile({35,-7},0,GRAY));
    walkable_tiles.push_back(Tile({36,-7},0,GRAY));
    borders_tiles.push_back(Tile({36,-7},0,GRAY));
    walkable_tiles.push_back(Tile({37,-7},0,GRAY));
    borders_tiles.push_back(Tile({37,-7},0,GRAY));
    walkable_tiles.push_back(Tile({38,-7},0,GRAY));
    borders_tiles.push_back(Tile({38,-7},0,GRAY));
    walkable_tiles.push_back(Tile({39,-7},0,GRAY));
    borders_tiles.push_back(Tile({39,-7},0,GRAY));
    walkable_tiles.push_back(Tile({40,-7},0,GRAY));
    borders_tiles.push_back(Tile({40,-7},0,GRAY));

    borders_tiles.push_back(Tile({12,-8},0,GRAY));
    walkable_tiles.push_back(Tile({13,-8},0,GRAY));
    walkable_tiles.push_back(Tile({14,-8},0,GRAY));
    walkable_tiles.push_back(Tile({15,-8},0,GRAY));
    walkable_tiles.push_back(Tile({16,-8},0,GRAY));
    walkable_tiles.push_back(Tile({17,-8},0,GRAY));
    walkable_tiles.push_back(Tile({18,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-8},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-8},0,GRAY));
    walkable_tiles.push_back(Tile({26,-8},0,GRAY));
    walkable_tiles.push_back(Tile({27,-8},0,GRAY));
    walkable_tiles.push_back(Tile({28,-8},0,GRAY));
    walkable_tiles.push_back(Tile({29,-8},0,GRAY));
    walkable_tiles.push_back(Tile({30,-8},0,GRAY));
    walkable_tiles.push_back(Tile({31,-8},0,GRAY));
    walkable_tiles.push_back(Tile({32,-8},0,GRAY));
    walkable_tiles.push_back(Tile({33,-8},0,GRAY));
    walkable_tiles.push_back(Tile({34,-8},0,GRAY));
    walkable_tiles.push_back(Tile({35,-8},0,GRAY));
    walkable_tiles.push_back(Tile({36,-8},0,GRAY));
    walkable_tiles.push_back(Tile({37,-8},0,GRAY));
    walkable_tiles.push_back(Tile({38,-8},0,GRAY));
    walkable_tiles.push_back(Tile({39,-8},0,GRAY));
    walkable_tiles.push_back(Tile({40,-8},0,GRAY));
    borders_tiles.push_back(Tile({40,-8},0,GRAY));

    borders_tiles.push_back(Tile({12,-9},0,GRAY));
    walkable_tiles.push_back(Tile({13,-9},0,GRAY));
    walkable_tiles.push_back(Tile({14,-9},0,GRAY));
    walkable_tiles.push_back(Tile({15,-9},0,GRAY));
    walkable_tiles.push_back(Tile({16,-9},0,GRAY));
    walkable_tiles.push_back(Tile({17,-9},0,GRAY));
    walkable_tiles.push_back(Tile({18,-9},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-9},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-9},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-9},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-9},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-9},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-9},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-9},0,GRAY));
    walkable_tiles.push_back(Tile({26,-9},0,GRAY));
    walkable_tiles.push_back(Tile({27,-9},0,GRAY));
    walkable_tiles.push_back(Tile({28,-9},0,GRAY));
    walkable_tiles.push_back(Tile({29,-9},0,GRAY));
    walkable_tiles.push_back(Tile({30,-9},0,GRAY));
    walkable_tiles.push_back(Tile({31,-9},0,GRAY));
    walkable_tiles.push_back(Tile({32,-9},0,GRAY));
    walkable_tiles.push_back(Tile({33,-9},0,GRAY));
    walkable_tiles.push_back(Tile({34,-9},0,GRAY));
    walkable_tiles.push_back(Tile({35,-9},0,GRAY));
    walkable_tiles.push_back(Tile({36,-9},0,GRAY));
    walkable_tiles.push_back(Tile({37,-9},0,GRAY));
    walkable_tiles.push_back(Tile({38,-9},0,GRAY));
    walkable_tiles.push_back(Tile({39,-9},0,GRAY));
    walkable_tiles.push_back(Tile({40,-9},0,GRAY));
    borders_tiles.push_back(Tile({40,-9},0,GRAY));

    borders_tiles.push_back(Tile({12,-10},0,GRAY));
    walkable_tiles.push_back(Tile({13,-10},0,GRAY));
    walkable_tiles.push_back(Tile({14,-10},0,GRAY));
    walkable_tiles.push_back(Tile({15,-10},0,GRAY));
    walkable_tiles.push_back(Tile({16,-10},0,GRAY));
    walkable_tiles.push_back(Tile({17,-10},0,GRAY));
    walkable_tiles.push_back(Tile({18,-10},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-10},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-10},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-10},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-10},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-10},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-10},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-10},0,GRAY));
    walkable_tiles.push_back(Tile({26,-10},0,GRAY));
    walkable_tiles.push_back(Tile({27,-10},0,GRAY));
    walkable_tiles.push_back(Tile({28,-10},0,GRAY));
    walkable_tiles.push_back(Tile({29,-10},0,GRAY));
    walkable_tiles.push_back(Tile({30,-10},0,GRAY));
    walkable_tiles.push_back(Tile({31,-10},0,GRAY));
    walkable_tiles.push_back(Tile({32,-10},0,GRAY));
    walkable_tiles.push_back(Tile({33,-10},0,GRAY));
    walkable_tiles.push_back(Tile({34,-10},0,GRAY));
    walkable_tiles.push_back(Tile({35,-10},0,GRAY));
    walkable_tiles.push_back(Tile({36,-10},0,GRAY));
    walkable_tiles.push_back(Tile({37,-10},0,GRAY));
    walkable_tiles.push_back(Tile({38,-10},0,GRAY));
    walkable_tiles.push_back(Tile({39,-10},0,GRAY));
    walkable_tiles.push_back(Tile({40,-10},0,GRAY));
    borders_tiles.push_back(Tile({40,-10},0,GRAY));

    borders_tiles.push_back(Tile({12,-11},0,GRAY));
    walkable_tiles.push_back(Tile({13,-11},0,GRAY));
    walkable_tiles.push_back(Tile({14,-11},0,GRAY));
    walkable_tiles.push_back(Tile({15,-11},0,GRAY));
    walkable_tiles.push_back(Tile({16,-11},0,GRAY));
    walkable_tiles.push_back(Tile({17,-11},0,GRAY));
    walkable_tiles.push_back(Tile({18,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-11},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-11},0,GRAY));
    walkable_tiles.push_back(Tile({26,-11},0,GRAY));
    walkable_tiles.push_back(Tile({27,-11},0,GRAY));
    walkable_tiles.push_back(Tile({28,-11},0,GRAY));
    walkable_tiles.push_back(Tile({29,-11},0,GRAY));
    walkable_tiles.push_back(Tile({30,-11},0,GRAY));
    walkable_tiles.push_back(Tile({31,-11},0,GRAY));
    walkable_tiles.push_back(Tile({32,-11},0,GRAY));
    walkable_tiles.push_back(Tile({33,-11},0,GRAY));
    walkable_tiles.push_back(Tile({34,-11},0,GRAY));
    walkable_tiles.push_back(Tile({35,-11},0,GRAY));
    walkable_tiles.push_back(Tile({36,-11},0,GRAY));
    walkable_tiles.push_back(Tile({37,-11},0,GRAY));
    walkable_tiles.push_back(Tile({38,-11},0,GRAY));
    walkable_tiles.push_back(Tile({39,-11},0,GRAY));
    walkable_tiles.push_back(Tile({40,-11},0,GRAY));
    borders_tiles.push_back(Tile({40,-11},0,GRAY));

    borders_tiles.push_back(Tile({12,-12},0,GRAY));
    walkable_tiles.push_back(Tile({13,-12},0,GRAY));
    walkable_tiles.push_back(Tile({14,-12},0,GRAY));
    walkable_tiles.push_back(Tile({15,-12},0,GRAY));
    walkable_tiles.push_back(Tile({16,-12},0,GRAY));
    walkable_tiles.push_back(Tile({17,-12},0,GRAY));
    walkable_tiles.push_back(Tile({18,-12},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-12},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-12},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-12},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-12},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-12},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-12},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-12},0,GRAY));
    walkable_tiles.push_back(Tile({26,-12},0,GRAY));
    walkable_tiles.push_back(Tile({27,-12},0,GRAY));
    walkable_tiles.push_back(Tile({28,-12},0,GRAY));
    borders_tiles.push_back(Tile({28,-12},0,GRAY));
    borders_tiles.push_back(Tile({29,-12},0,GRAY));
    borders_tiles.push_back(Tile({30,-12},0,GRAY));
    borders_tiles.push_back(Tile({31,-12},0,GRAY));
    borders_tiles.push_back(Tile({32,-12},0,GRAY));
    borders_tiles.push_back(Tile({33,-12},0,GRAY));
    borders_tiles.push_back(Tile({34,-12},0,GRAY));
    borders_tiles.push_back(Tile({35,-12},0,GRAY));
    borders_tiles.push_back(Tile({36,-12},0,GRAY));
    borders_tiles.push_back(Tile({37,-12},0,GRAY));
    borders_tiles.push_back(Tile({38,-12},0,GRAY));
    borders_tiles.push_back(Tile({39,-12},0,GRAY));
    borders_tiles.push_back(Tile({40,-12},0,GRAY));


    borders_tiles.push_back(Tile({12,-13},0,GRAY));
    walkable_tiles.push_back(Tile({13,-13},0,GRAY));
    walkable_tiles.push_back(Tile({14,-13},0,GRAY));
    walkable_tiles.push_back(Tile({15,-13},0,GRAY));
    walkable_tiles.push_back(Tile({16,-13},0,GRAY));
    walkable_tiles.push_back(Tile({17,-13},0,GRAY));
    walkable_tiles.push_back(Tile({18,-13},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-13},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-13},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-13},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-13},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-13},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-13},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-13},0,GRAY));
    walkable_tiles.push_back(Tile({26,-13},0,GRAY));
    walkable_tiles.push_back(Tile({27,-13},0,GRAY));
    walkable_tiles.push_back(Tile({28,-13},0,GRAY));
    borders_tiles.push_back(Tile({28,-13},0,GRAY));

    borders_tiles.push_back(Tile({12,-14},0,GRAY));
    walkable_tiles.push_back(Tile({13,-14},0,GRAY));
    walkable_tiles.push_back(Tile({14,-14},0,GRAY));
    walkable_tiles.push_back(Tile({15,-14},0,GRAY));
    walkable_tiles.push_back(Tile({16,-14},0,GRAY));
    walkable_tiles.push_back(Tile({17,-14},0,GRAY));
    walkable_tiles.push_back(Tile({18,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-14},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-14},0,GRAY));
    walkable_tiles.push_back(Tile({26,-14},0,GRAY));
    walkable_tiles.push_back(Tile({27,-14},0,GRAY));
    walkable_tiles.push_back(Tile({28,-14},0,GRAY));
    borders_tiles.push_back(Tile({28,-14},0,GRAY));

    borders_tiles.push_back(Tile({12,-15},0,GRAY));
    walkable_tiles.push_back(Tile({14,-15},0,GRAY));
    walkable_tiles.push_back(Tile({15,-15},0,GRAY));
    walkable_tiles.push_back(Tile({16,-15},0,GRAY));
    walkable_tiles.push_back(Tile({17,-15},0,GRAY));
    walkable_tiles.push_back(Tile({18,-15},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-15},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-15},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-15},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-15},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-15},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-15},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-15},0,GRAY));
    walkable_tiles.push_back(Tile({26,-15},0,GRAY));
    walkable_tiles.push_back(Tile({27,-15},0,GRAY));
    walkable_tiles.push_back(Tile({28,-15},0,GRAY));
    borders_tiles.push_back(Tile({28,-15},0,GRAY));

    borders_tiles.push_back(Tile({12,-16},0,GRAY));
    walkable_tiles.push_back(Tile({14,-16},0,GRAY));
    walkable_tiles.push_back(Tile({15,-16},0,GRAY));
    walkable_tiles.push_back(Tile({16,-16},0,GRAY));
    walkable_tiles.push_back(Tile({17,-16},0,GRAY));
    walkable_tiles.push_back(Tile({18,-16},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-16},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-16},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-16},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-16},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-16},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-16},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-16},0,GRAY));
    walkable_tiles.push_back(Tile({26,-16},0,GRAY));
    walkable_tiles.push_back(Tile({27,-16},0,GRAY));
    walkable_tiles.push_back(Tile({28,-16},0,GRAY));
    borders_tiles.push_back(Tile({28,-16},0,GRAY));

    borders_tiles.push_back(Tile({12,-17},0,GRAY));
    walkable_tiles.push_back(Tile({14,-17},0,GRAY));
    walkable_tiles.push_back(Tile({15,-17},0,GRAY));
    walkable_tiles.push_back(Tile({16,-17},0,GRAY));
    walkable_tiles.push_back(Tile({17,-17},0,GRAY));
    walkable_tiles.push_back(Tile({18,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-17},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-17},0,GRAY));
    walkable_tiles.push_back(Tile({26,-17},0,GRAY));
    walkable_tiles.push_back(Tile({27,-17},0,GRAY));
    walkable_tiles.push_back(Tile({28,-17},0,GRAY));
    borders_tiles.push_back(Tile({28,-17},0,GRAY));

    borders_tiles.push_back(Tile({12,-18},0,GRAY));
    walkable_tiles.push_back(Tile({14,-18},0,GRAY));
    walkable_tiles.push_back(Tile({15,-18},0,GRAY));
    walkable_tiles.push_back(Tile({16,-18},0,GRAY));
    walkable_tiles.push_back(Tile({17,-18},0,GRAY));
    walkable_tiles.push_back(Tile({18,-18},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-18},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-18},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-18},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-18},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-18},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-18},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-18},0,GRAY));
    walkable_tiles.push_back(Tile({26,-18},0,GRAY));
    walkable_tiles.push_back(Tile({27,-18},0,GRAY));
    walkable_tiles.push_back(Tile({28,-18},0,GRAY));
    borders_tiles.push_back(Tile({28,-18},0,GRAY));

    borders_tiles.push_back(Tile({12,-19},0,GRAY));
    walkable_tiles.push_back(Tile({14,-19},0,GRAY));
    walkable_tiles.push_back(Tile({15,-19},0,GRAY));
    walkable_tiles.push_back(Tile({16,-19},0,GRAY));
    walkable_tiles.push_back(Tile({17,-19},0,GRAY));
    walkable_tiles.push_back(Tile({18,-19},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-19},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-19},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-19},0,LIGHTGRAY));
    walkable_tiles.push_back(Tile({22,-19},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-19},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-19},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-19},0,GRAY));
    walkable_tiles.push_back(Tile({26,-19},0,GRAY));
    walkable_tiles.push_back(Tile({27,-19},0,GRAY));
    walkable_tiles.push_back(Tile({28,-19},0,GRAY));
    borders_tiles.push_back(Tile({28,-19},0,GRAY));

    borders_tiles.push_back(Tile({12,-20},0,GRAY));
    walkable_tiles.push_back(Tile({14,-20},0,GRAY));
    walkable_tiles.push_back(Tile({15,-20},0,GRAY));
    walkable_tiles.push_back(Tile({16,-20},0,GRAY));
    walkable_tiles.push_back(Tile({17,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({18,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({19,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({20,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({21,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({22,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({23,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({24,-20},0,DARKGRAY));
    walkable_tiles.push_back(Tile({25,-20},0,GRAY));
    walkable_tiles.push_back(Tile({26,-20},0,GRAY));
    walkable_tiles.push_back(Tile({27,-20},0,GRAY));
    walkable_tiles.push_back(Tile({28,-20},0,GRAY));
    borders_tiles.push_back(Tile({28,-20},0,GRAY));

    borders_tiles.push_back(Tile({12,-21},0,GRAY));
    borders_tiles.push_back(Tile({14,-21},0,GRAY));
    borders_tiles.push_back(Tile({15,-21},0,GRAY));
    borders_tiles.push_back(Tile({16,-21},0,GRAY));
    borders_tiles.push_back(Tile({17,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({18,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({19,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({20,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({21,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({22,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({23,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({24,-21},0,DARKGRAY));
    borders_tiles.push_back(Tile({25,-21},0,GRAY));
    borders_tiles.push_back(Tile({26,-21},0,GRAY));
    borders_tiles.push_back(Tile({27,-21},0,GRAY));
    borders_tiles.push_back(Tile({28,-21},0,GRAY));



    walkable_tiles.push_back(Tile({14,0},1,GRAY));
    walkable_tiles.push_back(Tile({15,0},1,GRAY));
    walkable_tiles.push_back(Tile({16,0},1,GRAY));
    walkable_tiles.push_back(Tile({17,0},1,GRAY));
    borders_tiles.push_back(Tile({17,0},1,GRAY));
    walkable_tiles.push_back(Tile({18,0},1,GRAY));
    walkable_tiles.push_back(Tile({19,0},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,0},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,0},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,0},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,0},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,0},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,0},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,0},1,GRAY));
    walkable_tiles.push_back(Tile({27,0},1,GRAY));
    walkable_tiles.push_back(Tile({28,0},1,GRAY));
    walkable_tiles.push_back(Tile({29,0},1,GRAY));
    walkable_tiles.push_back(Tile({30,0},1,GRAY));
    walkable_tiles.push_back(Tile({31,0},6,GRAY));
    borders_tiles.push_back(Tile({31,0},1,GRAY));
    walkable_tiles.push_back(Tile({32,0},8,GRAY));
    walkable_tiles.push_back(Tile({33,0},7,GRAY));
    walkable_tiles.push_back(Tile({34,0},6,GRAY));
    walkable_tiles.push_back(Tile({35,0},8,GRAY));
    walkable_tiles.push_back(Tile({36,0},7,GRAY));
    walkable_tiles.push_back(Tile({37,0},8,GRAY));
    walkable_tiles.push_back(Tile({38,0},7,GRAY));
    walkable_tiles.push_back(Tile({39,0},6,GRAY));
    walkable_tiles.push_back(Tile({40,0},7,GRAY));

    


    walkable_tiles.push_back(Tile({14,1},11,GRAY));
    walkable_tiles.push_back(Tile({15,1},11,GRAY));
    walkable_tiles.push_back(Tile({16,1},11,GRAY));
    walkable_tiles.push_back(Tile({17,1},11,GRAY));
    walkable_tiles.push_back(Tile({18,1},11,GRAY));
    borders_tiles.push_back(Tile({18,1},1,GRAY));
    walkable_tiles.push_back(Tile({19,1},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,1},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,1},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,1},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,1},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,1},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,1},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,1},1,GRAY));
    walkable_tiles.push_back(Tile({27,1},1,GRAY));
    walkable_tiles.push_back(Tile({28,1},1,GRAY));
    walkable_tiles.push_back(Tile({29,1},1,GRAY));
    walkable_tiles.push_back(Tile({30,1},1,GRAY));
    borders_tiles.push_back(Tile({31,1},1,GRAY));

    walkable_tiles.push_back(Tile({14,2},11,GRAY));
    walkable_tiles.push_back(Tile({15,2},11,GRAY));
    walkable_tiles.push_back(Tile({16,2},11,GRAY));
    walkable_tiles.push_back(Tile({17,2},11,GRAY));
    walkable_tiles.push_back(Tile({18,2},11,GRAY));
    borders_tiles.push_back(Tile({18,2},1,GRAY));
    walkable_tiles.push_back(Tile({19,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,2},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,2},1,GRAY));
    walkable_tiles.push_back(Tile({27,2},1,GRAY));
    walkable_tiles.push_back(Tile({28,2},1,GRAY));
    walkable_tiles.push_back(Tile({29,2},1,GRAY));
    walkable_tiles.push_back(Tile({30,2},1,GRAY));
    borders_tiles.push_back(Tile({31,2},1,GRAY));

    walkable_tiles.push_back(Tile({14,3},11,GRAY));
    walkable_tiles.push_back(Tile({15,3},11,GRAY));
    walkable_tiles.push_back(Tile({16,3},11,GRAY));
    walkable_tiles.push_back(Tile({17,3},11,GRAY));
    walkable_tiles.push_back(Tile({18,3},11,GRAY));
    borders_tiles.push_back(Tile({18,3},1,GRAY));
    walkable_tiles.push_back(Tile({19,3},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,3},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,3},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,3},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,3},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,3},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,3},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,3},1,GRAY));
    walkable_tiles.push_back(Tile({27,3},1,GRAY));
    walkable_tiles.push_back(Tile({28,3},1,GRAY));
    walkable_tiles.push_back(Tile({29,3},1,GRAY));
    walkable_tiles.push_back(Tile({30,3},1,GRAY));
    borders_tiles.push_back(Tile({31,3},1,GRAY));

    walkable_tiles.push_back(Tile({14,4},11,GRAY));
    walkable_tiles.push_back(Tile({15,4},11,GRAY));
    walkable_tiles.push_back(Tile({16,4},11,GRAY));
    walkable_tiles.push_back(Tile({17,4},11,GRAY));
    walkable_tiles.push_back(Tile({18,4},11,GRAY));
    borders_tiles.push_back(Tile({18,4},1,GRAY));
    walkable_tiles.push_back(Tile({19,4},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,4},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,4},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,4},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,4},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,4},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,4},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,4},1,GRAY));
    walkable_tiles.push_back(Tile({27,4},1,GRAY));
    walkable_tiles.push_back(Tile({28,4},1,GRAY));
    walkable_tiles.push_back(Tile({29,4},1,GRAY));
    walkable_tiles.push_back(Tile({30,4},1,GRAY));
    borders_tiles.push_back(Tile({31,4},1,GRAY));

    walkable_tiles.push_back(Tile({14,5},11,GRAY));
    walkable_tiles.push_back(Tile({15,5},11,GRAY));
    walkable_tiles.push_back(Tile({16,5},11,GRAY));
    walkable_tiles.push_back(Tile({17,5},11,GRAY));
    walkable_tiles.push_back(Tile({18,5},11,GRAY));
    borders_tiles.push_back(Tile({18,5},1,GRAY));
    walkable_tiles.push_back(Tile({19,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,5},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,5},1,GRAY));
    walkable_tiles.push_back(Tile({27,5},1,GRAY));
    walkable_tiles.push_back(Tile({28,5},1,GRAY));
    walkable_tiles.push_back(Tile({29,5},1,GRAY));
    walkable_tiles.push_back(Tile({30,5},1,GRAY));
    borders_tiles.push_back(Tile({31,5},1,GRAY));

    walkable_tiles.push_back(Tile({14,6},11,GRAY));
    walkable_tiles.push_back(Tile({15,6},11,GRAY));
    walkable_tiles.push_back(Tile({16,6},11,GRAY));
    walkable_tiles.push_back(Tile({17,6},11,GRAY));
    walkable_tiles.push_back(Tile({18,6},11,GRAY));
    borders_tiles.push_back(Tile({18,6},1,GRAY));
    walkable_tiles.push_back(Tile({19,6},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,6},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,6},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,6},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,6},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,6},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,6},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,6},1,GRAY));
    walkable_tiles.push_back(Tile({27,6},1,GRAY));
    walkable_tiles.push_back(Tile({28,6},1,GRAY));
    walkable_tiles.push_back(Tile({29,6},1,GRAY));
    walkable_tiles.push_back(Tile({30,6},1,GRAY));
    borders_tiles.push_back(Tile({31,6},1,GRAY));

    walkable_tiles.push_back(Tile({14,7},10,GRAY));
    walkable_tiles.push_back(Tile({15,7},10,GRAY));
    walkable_tiles.push_back(Tile({16,7},10,GRAY));
    walkable_tiles.push_back(Tile({17,7},10,GRAY));
    borders_tiles.push_back(Tile({17,7},1,GRAY));
    walkable_tiles.push_back(Tile({18,7},1,GRAY));
    walkable_tiles.push_back(Tile({19,7},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,7},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,7},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,7},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,7},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,7},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,7},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,7},1,GRAY));
    walkable_tiles.push_back(Tile({27,7},1,GRAY));
    walkable_tiles.push_back(Tile({28,7},1,GRAY));
    walkable_tiles.push_back(Tile({29,7},1,GRAY));
    walkable_tiles.push_back(Tile({30,7},1,GRAY));
    borders_tiles.push_back(Tile({31,7},1,GRAY));

    walkable_tiles.push_back(Tile({14,8},10,GRAY));
    walkable_tiles.push_back(Tile({15,8},10,GRAY));
    walkable_tiles.push_back(Tile({16,8},10,GRAY));
    walkable_tiles.push_back(Tile({17,8},10,GRAY));
    borders_tiles.push_back(Tile({17,8},1,GRAY));
    walkable_tiles.push_back(Tile({18,8},1,GRAY));
    walkable_tiles.push_back(Tile({19,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,8},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,8},1,GRAY));
    walkable_tiles.push_back(Tile({27,8},1,GRAY));
    walkable_tiles.push_back(Tile({28,8},1,GRAY));
    walkable_tiles.push_back(Tile({29,8},1,GRAY));
    walkable_tiles.push_back(Tile({30,8},1,GRAY));
    borders_tiles.push_back(Tile({31,8},1,GRAY));

    walkable_tiles.push_back(Tile({14,9},10,GRAY));
    walkable_tiles.push_back(Tile({15,9},10,GRAY));
    walkable_tiles.push_back(Tile({16,9},10,GRAY));
    walkable_tiles.push_back(Tile({17,9},10,GRAY));
    borders_tiles.push_back(Tile({17,9},1,GRAY));
    walkable_tiles.push_back(Tile({18,9},1,GRAY));
    walkable_tiles.push_back(Tile({19,9},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,9},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,9},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,9},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,9},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,9},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,9},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,9},1,GRAY));
    walkable_tiles.push_back(Tile({27,9},1,GRAY));
    walkable_tiles.push_back(Tile({28,9},1,GRAY));
    walkable_tiles.push_back(Tile({29,9},1,GRAY));
    walkable_tiles.push_back(Tile({30,9},1,GRAY));
    borders_tiles.push_back(Tile({31,9},1,GRAY));

    walkable_tiles.push_back(Tile({14,10},10,GRAY));
    walkable_tiles.push_back(Tile({15,10},10,GRAY));
    walkable_tiles.push_back(Tile({16,10},10,GRAY));
    borders_tiles.push_back(Tile({16,10},1,GRAY));
    walkable_tiles.push_back(Tile({17,10},10,GRAY));
    borders_tiles.push_back(Tile({17,10},1,GRAY));
    walkable_tiles.push_back(Tile({18,10},1.5,GRAY));
    walkable_tiles.push_back(Tile({19,10},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,10},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,10},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,10},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,10},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,10},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,10},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,10},1,GRAY));
    walkable_tiles.push_back(Tile({27,10},1,GRAY));
    walkable_tiles.push_back(Tile({28,10},1,GRAY));
    walkable_tiles.push_back(Tile({29,10},1,GRAY));
    walkable_tiles.push_back(Tile({30,10},1,GRAY));
    borders_tiles.push_back(Tile({31,10},1,GRAY));

    walkable_tiles.push_back(Tile({14,11},9,GRAY));
    borders_tiles.push_back(Tile({14,11},1,GRAY));
    walkable_tiles.push_back(Tile({15,11},9,GRAY));
    borders_tiles.push_back(Tile({15,11},1,GRAY));
    walkable_tiles.push_back(Tile({16,11},1,GRAY));
    walkable_tiles.push_back(Tile({17,11},1.5,GRAY));
    walkable_tiles.push_back(Tile({18,11},1.5,GRAY));
    walkable_tiles.push_back(Tile({19,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,11},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,11},1,GRAY));
    walkable_tiles.push_back(Tile({27,11},1,GRAY));
    walkable_tiles.push_back(Tile({28,11},1,GRAY));
    walkable_tiles.push_back(Tile({29,11},1,GRAY));
    walkable_tiles.push_back(Tile({30,11},1,GRAY));
    borders_tiles.push_back(Tile({31,11},1,GRAY));

    borders_tiles.push_back(Tile({14,12},1,GRAY));
    walkable_tiles.push_back(Tile({14,12},1,GRAY));
    walkable_tiles.push_back(Tile({15,12},1,GRAY));
    walkable_tiles.push_back(Tile({16,12},1,GRAY));
    walkable_tiles.push_back(Tile({17,12},1,GRAY));
    walkable_tiles.push_back(Tile({18,12},1,GRAY));
    walkable_tiles.push_back(Tile({19,12},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,12},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,12},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,12},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,12},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,12},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,12},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,12},1,GRAY));
    walkable_tiles.push_back(Tile({27,12},1,GRAY));
    walkable_tiles.push_back(Tile({28,12},1,GRAY));
    walkable_tiles.push_back(Tile({29,12},1,GRAY));
    walkable_tiles.push_back(Tile({30,12},1,GRAY));
    borders_tiles.push_back(Tile({31,12},1,GRAY));

    borders_tiles.push_back(Tile({14,13},1,GRAY));
    walkable_tiles.push_back(Tile({14,13},1,GRAY));
    walkable_tiles.push_back(Tile({15,13},1,GRAY));
    walkable_tiles.push_back(Tile({16,13},1,GRAY));
    walkable_tiles.push_back(Tile({17,13},1,GRAY));
    walkable_tiles.push_back(Tile({18,13},1,GRAY));
    walkable_tiles.push_back(Tile({19,13},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,13},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,13},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,13},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,13},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,13},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,13},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,13},1,GRAY));
    walkable_tiles.push_back(Tile({27,13},1,GRAY));
    walkable_tiles.push_back(Tile({28,13},1,GRAY));
    walkable_tiles.push_back(Tile({29,13},1,GRAY));
    walkable_tiles.push_back(Tile({30,13},1,GRAY));
    borders_tiles.push_back(Tile({31,13},1,GRAY));

    borders_tiles.push_back(Tile({14,14},1,GRAY));
    walkable_tiles.push_back(Tile({14,14},1,GRAY));
    walkable_tiles.push_back(Tile({15,14},1,GRAY));
    walkable_tiles.push_back(Tile({16,14},1,GRAY));
    walkable_tiles.push_back(Tile({17,14},1,GRAY));
    walkable_tiles.push_back(Tile({18,14},1,GRAY));
    walkable_tiles.push_back(Tile({19,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,14},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,14},1,GRAY));
    walkable_tiles.push_back(Tile({27,14},1,GRAY));
    walkable_tiles.push_back(Tile({28,14},1,GRAY));
    walkable_tiles.push_back(Tile({29,14},1,GRAY));
    walkable_tiles.push_back(Tile({30,14},1,GRAY));
    borders_tiles.push_back(Tile({31,14},1,GRAY));

    walkable_tiles.push_back(Tile({14,15},1,GRAY));
    walkable_tiles.push_back(Tile({15,15},1,GRAY));
    walkable_tiles.push_back(Tile({16,15},1,GRAY));
    walkable_tiles.push_back(Tile({17,15},1,GRAY));
    walkable_tiles.push_back(Tile({18,15},1,GRAY));
    walkable_tiles.push_back(Tile({19,15},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,15},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,15},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,15},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,15},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,15},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,15},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,15},1,GRAY));
    walkable_tiles.push_back(Tile({27,15},1,GRAY));
    walkable_tiles.push_back(Tile({28,15},1,GRAY));
    walkable_tiles.push_back(Tile({29,15},1,GRAY));
    walkable_tiles.push_back(Tile({30,15},1,GRAY));
    borders_tiles.push_back(Tile({31,15},1,GRAY));

    walkable_tiles.push_back(Tile({14,16},1,GRAY));
    walkable_tiles.push_back(Tile({15,16},1,GRAY));
    borders_tiles.push_back(Tile({15,16},1,GRAY));
    walkable_tiles.push_back(Tile({16,16},1,GRAY));
    walkable_tiles.push_back(Tile({17,16},1,GRAY));
    walkable_tiles.push_back(Tile({18,16},1,GRAY));
    walkable_tiles.push_back(Tile({19,16},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,16},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,16},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,16},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,16},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,16},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,16},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,16},1,GRAY));
    walkable_tiles.push_back(Tile({27,16},1,GRAY));
    walkable_tiles.push_back(Tile({28,16},1,GRAY));
    walkable_tiles.push_back(Tile({29,16},1,GRAY));
    walkable_tiles.push_back(Tile({30,16},1,GRAY));
    borders_tiles.push_back(Tile({31,16},1,GRAY));

    walkable_tiles.push_back(Tile({14,17},1,GRAY));
    walkable_tiles.push_back(Tile({15,17},1,GRAY));
    walkable_tiles.push_back(Tile({16,17},1,GRAY));
    borders_tiles.push_back(Tile({16,17},1,GRAY));
    walkable_tiles.push_back(Tile({17,17},1,GRAY));
    walkable_tiles.push_back(Tile({18,17},1,GRAY));
    walkable_tiles.push_back(Tile({19,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,17},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,17},1,GRAY));
    walkable_tiles.push_back(Tile({27,17},1,GRAY));
    walkable_tiles.push_back(Tile({28,17},1,GRAY));
    walkable_tiles.push_back(Tile({29,17},1,GRAY));
    borders_tiles.push_back(Tile({30,17},1,GRAY));

    
    walkable_tiles.push_back(Tile({14,18},1,GRAY));
    walkable_tiles.push_back(Tile({15,18},1,GRAY));
    walkable_tiles.push_back(Tile({16,18},1,GRAY));
    walkable_tiles.push_back(Tile({17,18},1,GRAY));
    borders_tiles.push_back(Tile({17,18},1,GRAY));
    walkable_tiles.push_back(Tile({18,18},1,GRAY));
    walkable_tiles.push_back(Tile({19,18},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,18},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,18},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,18},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,18},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,18},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,18},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,18},1,GRAY));
    walkable_tiles.push_back(Tile({27,18},1,GRAY));
    walkable_tiles.push_back(Tile({28,18},1,GRAY));
    walkable_tiles.push_back(Tile({29,18},1,GRAY));
    borders_tiles.push_back(Tile({30,18},1,GRAY));

    walkable_tiles.push_back(Tile({14,19},1,GRAY));
    walkable_tiles.push_back(Tile({15,19},1,GRAY));
    walkable_tiles.push_back(Tile({16,19},1,GRAY));
    walkable_tiles.push_back(Tile({17,19},1,GRAY));
    walkable_tiles.push_back(Tile({18,19},1,GRAY));
    borders_tiles.push_back(Tile({18,19},1,GRAY));
    walkable_tiles.push_back(Tile({19,19},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,19},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,19},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,19},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,19},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,19},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,19},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,19},1,GRAY));
    walkable_tiles.push_back(Tile({27,19},1,GRAY));
    walkable_tiles.push_back(Tile({28,19},1,GRAY));
    walkable_tiles.push_back(Tile({29,19},1,GRAY));
    borders_tiles.push_back(Tile({30,19},1,GRAY));

    walkable_tiles.push_back(Tile({14,20},1,GRAY));
    walkable_tiles.push_back(Tile({15,20},1,GRAY));
    walkable_tiles.push_back(Tile({16,20},1,GRAY));
    walkable_tiles.push_back(Tile({17,20},1,GRAY));
    walkable_tiles.push_back(Tile({18,20},1,GRAY));
    walkable_tiles.push_back(Tile({19,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({20,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({23,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,20},1,DARKGRAY));
    walkable_tiles.push_back(Tile({26,20},1,GRAY));
    walkable_tiles.push_back(Tile({27,20},1,GRAY));
    walkable_tiles.push_back(Tile({28,20},1,GRAY));
    walkable_tiles.push_back(Tile({29,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));
    borders_tiles.push_back(Tile({30,20},1,GRAY));    

    

    borders_tiles.push_back(Tile({20,21},1,DARKGRAY));
    walkable_tiles.push_back(Tile({21,21},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,21},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,21},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,21},1,DARKGRAY));
    walkable_tiles.push_back(Tile({25,21},1,DARKGRAY));
    borders_tiles.push_back(Tile({26,21},1,GRAY));
    borders_tiles.push_back(Tile({27,21},1,GRAY));
    borders_tiles.push_back(Tile({28,21},1,GRAY));
    borders_tiles.push_back(Tile({29,21},1,GRAY));



    borders_tiles.push_back(Tile({21,22},1,DARKGRAY));
    walkable_tiles.push_back(Tile({22,22},1,LIGHTGRAY));
    walkable_tiles.push_back(Tile({23,22},1,DARKGRAY));
    walkable_tiles.push_back(Tile({24,22},1,DARKGRAY));
    borders_tiles.push_back(Tile({25,22},1,GRAY));




    borders_tiles.push_back(Tile({22,23},1,GRAY));
    walkable_tiles.push_back(Tile({23,23},1,DARKGRAY));
    borders_tiles.push_back(Tile({24,23},1,GRAY));





    

}

// Draws the entire map as a grid of tiles
void Map::draw_map() {
    
    //walkable_tiles.push_back(Tile({15,5},1,GRAY,true));
    for(auto& tile:walkable_tiles){
        tile.draw();
    }
    for(auto& tile:no_walkable_tiles){
        tile.draw();
    }


}

bool Map::is_walkable(Rectangle screenPos) {
    for(auto& tile:no_walkable_tiles){
        bool collision = tile.checkRectangleLineCollision(screenPos,tile.collisionEdges);
        if(collision){
            return false;
        }
    }
    for(auto& tile:borders_tiles){
        bool collision = tile.checkRectangleLineCollision(screenPos,tile.collisionEdges);
        if(collision){
            return false;
        }
    }
    return true;
}
